version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passqqaazz!1
      POSTGRES_DB: archimedes
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
      npm run db:migrate &&
      npm start
      "

volumes:
  pgdata:
