const NotificationsErrorCodes = {
  NOTIFICATIONS_DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  NOTIFICATIONS_PLATFORM_NOT_VALID: 'NOTIFICATIONS_PLATFORM_NOT_VALID',
} as const;

const MisErrorCodes = {
  MIS_PATIENT_NOT_FOUND: 'MIS_PATIENT_NOT_FOUND',
  MIS_SPECIALTY_NOT_FOUND: 'MIS_SPECIALTY_NOT_FOUND',
  MIS_CREATE_APPOINTMENT_FAILED: 'MIS_CREATE_APPOINTMENT_FAILED',
  MIS_PATIENT_HAS_NO_INSURANCE: 'MIS_PATIENT_HAS_NO_INSURANCE',
};

const AppointmentErrorCodes = {
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_DATE_CONFLICT: 'APPOINTMENT_DATE_CONFLICT',
  APPOINTMENT_DOCTOR_UNAVAILABLE: 'APPOINTMENT_DOCTOR_UNAVAILABLE',
  APPOINTMENT_ACCESS_DENIED: 'APPOINTMENT_ACCESS_DENIED',
} as const;

const AdminErrorCodes = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
  TOO_MANY_LOGIN_ATTEMPTS: 'TOO_MANY_LOGIN_ATTEMPTS',
} as const;

export const ErrorCodes = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_OTP: 'INVALID_OTP',
  FORBIDDEN: 'FORBIDDEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  INVALID_REGISTRATION_TOKEN: 'INVALID_REGISTRATION_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_VERIFICATION_FAILED: 'TOKEN_VERIFICATION_FAILED',
  SESSION_REPLACED: 'SESSION_REPLACED',
  AUTHORIZATION_HEADER_MISSING: 'AUTHORIZATION_HEADER_MISSING',
  OTP_EXPIRED: 'OTP_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  INVALID_PIN_FORMAT: 'INVALID_PIN_FORMAT',
  INVALID_PIN: 'INVALID_PIN',
  PIN_NOT_SET: 'PIN_NOT_SET',
  PIN_LOCKED: 'PIN_LOCKED',
  PATIENT_PROFILE_NOT_FOUND: 'PATIENT_PROFILE_NOT_FOUND',
  INSURANCE_USER_NOT_FOUND: 'INSURANCE_USER_NOT_FOUND',
  INSURANCE_USER_NOT_AUTHORIZED: 'INSURANCE_USER_NOT_AUTHORIZED',
  INSURANCE_REFUND_FAILED: 'INSURANCE_REFUND_FAILED',
  INSURANCE_SERVICE_TOKEN_NOT_FOUND: 'INSURANCE_SERVICE_TOKEN_NOT_FOUND',
  INSURANCE_PROGRAMS_NOT_FOUND: 'INSURANCE_PROGRAMS_NOT_FOUND',
  INSURANCE_FAMILY_INFO_NOT_FOUND: 'INSURANCE_FAMILY_INFO_NOT_FOUND',
  INSURANCE_REFUND_REQUESTS: 'INSURANCE_REFUND_REQUESTS',
  INSURANCE_NOT_FOUND_IN_MIS: 'INSURANCE_NOT_FOUND_IN_MIS',
  INSURANCE_PHONE_IS_NOT_MATCHED: 'INSURANCE_PHONE_IS_NOT_MATCHED',
  CHECKUP_NOT_FOUND: 'CHECKUP_NOT_FOUND',
  CHECKUP_CODE_TAKEN: 'CHECKUP_CODE_TAKEN',
  PROGRAM_ORDER_NOT_FOUND: 'PROGRAM_ORDER_NOT_FOUND',
  PROGRAM_ORDER_PRICE_CHANGED: 'PROGRAM_ORDER_PRICE_CHANGED',
  PROGRAM_ORDER_TOTAL_MISMATCH: 'PROGRAM_ORDER_TOTAL_MISMATCH',
  ...AdminErrorCodes,
  ...NotificationsErrorCodes,
  ...MisErrorCodes,
  ...AppointmentErrorCodes,
} as const;
