export const ErrorCodes = {
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_OTP: 'INVALID_OTP',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_VERIFICATION_FAILED: 'TOKEN_VERIFICATION_FAILED',
  AUTHORIZATION_HEADER_MISSING: 'AUTHORIZATION_HEADER_MISSING',
  OTP_EXPIRED: 'OTP_EXPIRED',
} as const;
